### PR TITLE
Indents

### PR DESCRIPTION
**Pull request by zdm**

### CODE REVIEW

**Comment by perlpunk** [comment]
@zdm Could you please add a test?
And add a variable declaration to `lib/YAML/XS.pm` so that we don't get a warning `Name "YAML::XS::Indent" used only once: possible typo`

**Comment by zdm** [comment]
Will do

**Comment by zdm** [comment]
@perlpunk Done

**Comment by zdm** [comment]
@perlpunk 
Sorry, I am too hurried last time and committed tests with errors.
Now it's passing all checks.
Could you, please, accept this PR and make release on CPAN?

**Comment by perlpunk** [comment]
thanks, merged!
I squashed and amended your commits (removed `$YAML::Indent` to be consistent because that's not how the other variables work right now)

**Comment by zdm** [comment]
@perlpunk 
Could you, please, release it, so people (and me ;-)) can use it?
Thank you.

**Comment by zdm** [comment]
Thanks

**Pull request closed without merging**
