### PR TITLE
Recognise core booleans on Perl 5.36+ at dump time (Fixes #113)

### LINKED ISSUE #113: Support proper booleans on Perl 5.36+
Since Perl 5.36, we've been able to distinguish actual boolean values. It'd be great if YAML::XS emitted these distinctly.

Currently this gives disappointing results:

```
$ eachperl modversion YAML::XS
perl5.36.0: 0.88
perl5.38.0: 0.88
bleadperl: 0.88

$ eachperl -MYAML::XS -E 'say YAML::XS::Dump([1, "1", builtin::true])'

  --- perl5.36.0 --- 
Built-in function 'builtin::true' is experimental at -e line 1.
---
- 1
- '1'
- 1


  --- perl5.38.0 --- 
Built-in function 'builtin::true' is experimental at -e line 1.
---
- 1
- '1'
- 1


  --- bleadperl --- 
---
- 1
- '1'
- 1
```

I would love to have seen the output be:

```
---
- 1
- '1'
- true
```

### PR DESCRIPTION
**Pull request by leonerd**
Unsure if you'll be happy with the exact layout and formatting of this, but this is the basic idea.

### CODE REVIEW

**Review by perlpunk — APPROVED** [review]

**Comment by perlpunk** [comment]
This needs #115

**Comment by leonerd** [comment]
Now that this is rebased atop #115 is this good to go?

**Review by ingydotnet — APPROVED** [review]

**Comment by leonerd** [comment]
I see this is now merged. Will there be a new CPAN release of the module soon? Ideally I'd like to mention it in my FOSDEM talk, in two weeks time.

**Comment by perlpunk** [comment]
yes, it will be released in the next few days

**Comment by perlpunk** [comment]
hope to meet you at fosdem :)

**Comment by perlpunk** [comment]
Released: https://metacpan.org/release/TINITA/YAML-LibYAML-0.89
thanks =)

**Pull request merged**
