### PR TITLE
fix a C90-compatibility issue

### PR DESCRIPTION
**Pull request by stphnlyd**

### CODE REVIEW

**Comment by perlpunk** [comment]
Thanks, applied!

**Comment by bulk88** [comment]
LibYAML needs a CPAN release quickly. I can't build 0.67-0.69 (latest) with Visual C compiler because of https://github.com/ingydotnet/yaml-libyaml-pm/commit/ed73226e49686a150916bd2d941e28e276b2aab6#diff-5b946a680425c87cbbf1de37bc82b03d 

```
cl -c  -I.      -nologo -GF -W3 -O1 -MD -Zi -DNDEBUG -G7 -GL -DWIN32 -D_CONSOLE
-DNO_STRICT -DPERL_HASH_FUNC_ONE_AT_A_TIME -DNO_MATHOMS -DPERL_DISABLE_PMC -DPER
L_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DWIN32_NO_REGIST
RY -D_USE_32BIT_TIME_T -O1 -MD -Zi -DNDEBUG -G7 -GL       -DVERSION=\"\"
-DXS_VERSION=\"\"  "-IC:\perl528\lib\CORE"  -DHAVE_CONFIG_H -DYAML_DECLARE_EXPOR
T -Fdperl_libyaml.pdb perl_libyaml.c
perl_libyaml.c
perl_libyaml.c(613) : error C2143: syntax error : missing ';' before 'type'
perl_libyaml.c(617) : error C2065: 'boolean' : undeclared identifier
perl_libyaml.c(617) : warning C4047: '=' : 'int' differs in levels of indirectio
n from 'char *'
perl_libyaml.c(618) : warning C4047: 'function' : 'const char *' differs in leve
ls of indirection from 'int'
perl_libyaml.c(622) : warning C4047: 'function' : 'const char *' differs in leve
ls of indirection from 'int'
dmake:  Error code 130, while making 'perl_libyaml.obj'
dmake:  Error code 255, while making 'subdirs'
  TINITA/YAML-LibYAML-0.69.tar.gz
  dmake -- NOT OK
Failed during this command:
 TINITA/YAML-LibYAML-0.69.tar.gz              : make NO
```

**Comment by perlpunk** [comment]
I'm sorry, will release tonight hopefully

**Comment by perlpunk** [comment]
@bulk88 released v0.70

**Pull request merged**
