### PR TITLE
Allow reading and writing to IO::Handle (and derived) objects

### PR DESCRIPTION
**Pull request by lameventanas**
This change allows using IO::Handle derived objects.
IO::Pipe and IO::File tests included.

### CODE REVIEW

**Comment by lameventanas** [comment]
Same as pull request #35, but without Test::YAML.

**Comment by ingydotnet** [comment]
@perlpunk and I tried to merge this but we needed to fix a few things and the
tests still failed.

We pushed our changes to https://github.com/ingydotnet/yaml-libyaml-pm/tree/issue/36

Your tests need to go under the test/ dir. This module uses Zilla::Dist.
Install that module and then run your tests with:

    zild disttest

You can also try `zild distshell` if you want to interact with the generated
dist.

Hopefully you can get this working. Thanks for the effort.

**Comment by lameventanas** [comment]
For me zild doesn't work at all, even in the master branch.
This is the output from zild disttest (with some flags I added to Dist/Zilla/Plugin/TestBaseIncluder.pm):
https://gist.githubusercontent.com/lameventanas/0a6fd0429337bf065409/raw/ea071c2fd2b876cc8b1a5e7a4a7f6aae538b83a9/gistfile1.txt

**Comment by perlpunk** [comment]
@lameventanas you have to checkout test-base-pm for the test
 @ingydotnet I got the test working by removing `:utf8' mode. YAML::XS handles the encoding.
I created PR #37 for this branch.

**Comment by ingydotnet** [comment]
Applied. Released. Thanks!

Fixed by #37 plus a ingy^tina bug fix

**Pull request merged**
